--NGUYỄN TẤN PHA 22/04/2000 3001181179 18CDTH1
--PHẠM TRƯỜNG PHÚC 13/09/2000 3001180848  18CDTH1
--LÊ HOÀNG PHÚC 12/06/2000 3001181854  18CDTH1

	CREATE DATABASE QL_THICCNGANHANTIEPTHEO ON PRIMARY 
(  
	NAME = 'DL_THICCNGANHANTIEPTHEO',
	FILENAME = 'E:\baitapdoan\QL_THICCNGANHANTIEPTHEO_PRIMARY.mdf',
    SIZE = 5 MB,  MAXSIZE = 10 MB,  FILEGROWTH = 10% 
)
 LOG ON 
(  
	NAME = 'DL_THICCNGANHANTIEPTHEO_LOG',
	FILENAME = 'E:\baitapdoan\QL_THICCNGANHANTIEPTHEO_LOG.ldf',
	SIZE = 2 MB,
	MAXSIZE = 5 MB, 
	FILEGROWTH = 15%
) 
CREATE TABLE LOAICC_CDL
(
	MALOAICC NCHAR(10) NOT NULL,
	TENLOAICC NVARCHAR (50),
	SOMONTP INT,
	TGIANTHICC INT,
	TIEN MONEY,
	CONSTRAINT PK_LOAICC PRIMARY KEY (MALOAICC) 
)
CREATE TABLE MONTHANHPHAN_CDL
(
	MAMONTP NCHAR(10) NOT NULL,
	TENMON NVARCHAR (50),
	THOIGIANTHI INT,
	MALOAICC NCHAR(10),
	CONSTRAINT PK_MONTHANHPHAN PRIMARY KEY (MAMONTP),
	CONSTRAINT FK_MONTHANHPHAN_LOAICC FOREIGN KEY (MALOAICC) REFERENCES LOAICC_CDL(MALOAICC)
)
CREATE TABLE THISINH_CDL
(
    MATS NCHAR(10) NOT NULL,
	HOTEN NVARCHAR(50),
	NGAYSINH DATE,
	PHAI NCHAR(10),
	DIEMTB INT,
	KQ INT,
	XEPLOAI NCHAR(10),
	CONSTRAINT PK_THISINH PRIMARY KEY (MATS),
)

-- VIẾT LỆNH BULK CHUYỂN DỮ LIỆU TRONG EXCEL ĐƯỢC XUẤT RA TỪ BẢNG THISINH VÀO BẢNG THISINH_CDL
BULK INSERT THISINH_CDL
FROM 'E:\baitapdoan\THISINH.xls'
WITH
(
	ROWTERMINATOR ='\n',
	FIELDTERMINATOR = ',',
	FIRSTROW =2
)
-- VIẾT LỆNH BULK CHUYỂN DỮ LIỆU TRONG EXCEL ĐƯỢC XUẤT RA TỪ BẢNG LOAICC VÀO BẢNG LOAICC_CDL
BULK INSERT LOAICC_CDL
FROM 'E:\baitapdoan\LOAICC.xls'
WITH
(
	ROWTERMINATOR ='\n',
	FIELDTERMINATOR = ',',
	FIRSTROW =2
)
-- VIẾT LỆNH BULK CHUYỂN DỮ LIỆU TRONG EXCEL ĐƯỢC XUẤT RA TỪ BẢNG MONTHANHPHAN VÀO BẢNG MONTHANHPHAN_CDL
BULK INSERT MONTHANHPHAN_CDL
FROM 'E:\baitapdoan\MONTHANHPHAN.xls'
WITH
(
	ROWTERMINATOR ='\n',
	FIELDTERMINATOR = ',',
	FIRSTROW =2
)
--BACKUP FULL 
BACKUP DATABASE QL_THICCNGANHANTIEPTHEO
TO DISK='E:\baitapdoan\BACKUP\QL_THICCNGANHANCHUYENDL.BAK'
--PHỤC HỒI BẢN FULL
RESTORE DATABASE QL_THICCNGANHANTIEPTHEO
FROM DISK='E:\baitapdoan\BACKUP\QL_THICCNGANHANCHUYENDL.BAK'


